name: Python Unit Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Run Python Unit Tests
        run: python3.9 -m unittest